### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by tkralphs** [aykutbulut/COLA#5]
Travis build is still failing because `cblas.h` is not found. I'm not sure how to fix this. I tried to look at how Blas is being used in `CoinUtils` and `Clp`, but couldn't see what's going on quickly. Can you take a look?

**Comment by tkralphs** [comment]
I added installation of Debian package `libblas-dev` to get `cblas.h` and now I'm getting
```
./.libs/libCola.so: undefined reference to `dposv_'
```

**Comment by aykutbulut** [comment]
I added liblapack-dev and Linux build works fine. OSX still fails due to lack of blas and lapack.

**Comment by tkralphs** [comment]
It's not the lack of bals and lapack that is the problem, it is that you are depending on a particular distribution of lapack and blas. You have referencing the header file `cblas.h`, which isn't part of the standard source distribution. OS X has blas and lapack built into the OS, so it is there, you just need to link to it properly.

**Comment by aykutbulut** [comment]
I fixed it. Closing the issue.
